### PR TITLE
Limit background animation's FPS

### PR DESCRIPTION
**Pull request by gingerphoenix10**
Potential fix for https://github.com/p2r3/epochtal/issues/46. The dot's movement speed may also need to be multiplied.

Hopefully I used git correctly this time 🙏🙏🙏

### CODE REVIEW

**Comment by PancakeTAS** [comment]
yeah I'm gonna be honest... this looks like a terrible way to fix the issue..
there's gotta a better way than relying on the inconsistent and unprecise system clock (it's updated ever 1-2ms on linux and 4ms on windows)

**Comment by p2r3** [comment]
Checking `Date.now()` every frame and ensuring enough time has elapsed between frames would be my proposed implementation.

**Comment by gingerphoenix10** [comment]
Yeahh, I was guessing there was a better way. I was just trying to make a fix that _would_ increase performance, but would also be small enough to where I wasn't replacing or adding too much code. Wasn't expecting this to be a permanent solution or anything.

**Comment by PolarizedIons** [comment]
According to MDN, there I already an *elapsed* parameter passed to your call callback, so just count that up, until you get to a reasonable delay between animation frames 

https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame#examples

**Pull request closed without merging**
